### ISSUE TITLE
Переделать тексты на начало\окончание матча

### ISSUE THREAD

**Issue by yaporyvaev** [yaporyvaev/Oracles-Lens#2]
Необходимо переделать форматирование и текст на событиях начала и окончания матча.

- [x] Сформулировать тексты
- [x] Настроить форматирование с переносом строк
- [x] Заменить ники на имена (?)

**Comment by desoleilone** [comment]
Стас Токсик

**Comment by yaporyvaev** [comment]
> Стас Токсик

Што ето значит?

**Comment by desoleilone** [comment]
То и значит, просто факт, который он, возможно, никогда не увидит.
